apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: weaviate-operator
  template:
    metadata:
      labels:
        name: weaviate-operator
    spec:
      serviceAccountName: weaviate-operator
      containers:
        - name: weaviate-operator
          # Replace this with the built image name
          image: quay.io/jcordes/weaviate-operator:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "weaviate-operator"
