apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: weaviates.semi.com
spec:
  group: semi.com
  names:
    kind: Weaviate
    listKind: WeaviateList
    plural: weaviates
    singular: weaviate
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
