apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weaviate
  labels:
    name: weaviate
spec:
  progressDeadlineSeconds: 1200
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
        - name: weaviate
          image: '{{ .Values.image.registry }}semitechnologies/weaviate:{{ .Values.image.tag }}'
          ports:
            - containerPort: 8080
          args:
            - '--host'
            - '0.0.0.0'
            - '--port'
            - '8080'
            - '--scheme'
            - 'http'
            - '--config-file'
            - '/weaviate-config/conf.yaml'
          volumeMounts:
            - name: weaviate-config
              mountPath: /weaviate-config
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: weaviate-config
          configMap:
            name: weaviate-config
