dependencies:
  - name: elasticsearch
    version: 7.2.1-0
    repository: 'https://helm.elastic.co'
    alias: esvector

  - name: etcd
    version: 3.1.1
    repository: 'https://charts.bitnami.com/bitnami'
    alias: etcd
    condition: etcd.deploy

